MyAcademyCarBook.PresentationLayer/Controllers/BrandController.cs
using Microsoft.AspNetCore.Mvc;
using MyAcademyCarBook.BusinessLayer.Abstract;
using MyAcademyCarBook.EntityLayer.Concrete;

namespace MyAcademyCarBook.PresentationLayer.Controllers
{
    public class BrandController : Controller
    {
        private readonly IBrandService _brandService;

        public BrandController(IBrandService brandService)
        {
            _brandService = brandService;
        }

        public IActionResult Index()
        {
            var values = _brandService.TGetListAll();
            return View(values);
        }
        [HttpGet]
        public IActionResult AddBrand()
        {
            return View();
        }
        [HttpPost]
        public IActionResult AddBrand(Brand brand)
        {
            _brandService.TInsert(brand);
            return RedirectToAction("Index");
        }
        public IActionResult DeleteBrand(int id)
        {
            var value = _brandService.TGetByID(id);
            _brandService.TDelete(value);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult UpdateBrand(int id)
        {
            var value = _brandService.TGetByID(id);
            return View(value);
        }
        [HttpPost]
        public IActionResult UpdateBrand(Brand brand)
        {
            _brandService.TUpdate(brand);
            return RedirectToAction("Index");
        }
        public IActionResult GetBrandSearchByName(string p)
        {
            ViewData["CurrentFilter"] = p;
            var values = from x in _brandService.TGetListAll() select x;
            if(!string.IsNullOrEmpty(p))
            {
                values = values.Where(y => y.BrandName.Contains(p));
            }
            return View(values.ToList());
        }
    }
}

MyAcademyCarBook.PresentationLayer/Views/Brand/AddBrand.cshtml
@model MyAcademyCarBook.EntityLayer.Concrete.Brand
@{
    ViewData["Title"] = "AddBrand";
    Layout = "~/Views/AdminLayout/Index.cshtml";
}

<h3>Yeni Marka Girişi</h3>

<form method="post">
    <label>Marka Adı</label>
    <input type="text" asp-for="BrandName" class="form-control"  style="border:1px solid #2222"/>
    <br />
    <button class="btn btn-primary">Markayı Kaydet</button>
</form>

MyAcademyCarBook.PresentationLayer/Views/Brand/GetBrandSearchByName.cshtml
@model List<MyAcademyCarBook.EntityLayer.Concrete.Brand>
@{
    Layout = "~/Views/AdminLayout/Index.cshtml";
}

<form asp-action="GetBrandSearchByName" method="get" asp-controller="Brand">
    <div>
        <p>
            <b>Lütfen Marka Adını Giriniz:</b> <input type="text" name="p" value="@ViewData["CurrentFilter"]" class="form-control" style="border:1px solid #2222" />
            <br />
            <input type="submit" class="btn btn-dark" value="Marka Getir"
        </p>
    </div>
</form>

<table class=" table table-bordered">
    <tr>
        <th>#</th>
        <th>Marka Adı</th>
        <th>Durum</th>
        <th>Sil</th>
        <th>Güncelle</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.BrandID</td>
            <td>@item.BrandName</td>
            <td>@item.Status</td>
            <td><a href="/Brand/DeleteBrand/@item.BrandID" class="btn btn-danger">Sil</a></td>
            <td><a href="/Brand/UpdateBrand/@item.BrandID" class="btn btn-success">Güncelle</a></td>
        </tr>
    }
</table>
<a href="#" class="btn btn-primary">Yeni Marka Girişi</a>

MyAcademyCarBook.PresentationLayer/Views/Brand/Index.cshtml
@model List<MyAcademyCarBook.EntityLayer.Concrete.Brand>
@{
    Layout = "~/Views/AdminLayout/Index.cshtml";
}

<br />
<br />
<table class=" table table-bordered">
    <tr>
        <th>#</th>
        <th>Marka Adı</th>
        <th>Durum</th>
        <th>Sil</th>
        <th>Güncelle</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.BrandID</td>
            <td>@item.BrandName</td>
            <td>@item.Status</td>
            <td><a href="/Brand/DeleteBrand/@item.BrandID" class="btn btn-danger">Sil</a></td>
            <td><a href="/Brand/UpdateBrand/@item.BrandID" class="btn btn-success">Güncelle</a></td>
        </tr>
    }
</table>
<a href="#" class="btn btn-primary">Yeni Marka Girişi</a>

MyAcademyCarBook.PresentationLayer/Views/Brand/UpdateBrand.cshtml
@model MyAcademyCarBook.EntityLayer.Concrete.Brand
@{
    ViewData["Title"] = "UpdateBrand";
    Layout = "~/Views/AdminLayout/Index.cshtml";
}

<h3>Marka Güncelleme Sayfası</h3>

<form method="post">
    <input type="hidden" asp-for="BrandID" />
    <label>Marka Adı</label>
    <input type="text" asp-for="BrandName" class="form-control" style="border:1px solid #2222" />
    <br />
    <button class="btn btn-success">Güncelle</button>
</form>